### PR TITLE
allow future IntelliJ versions

### PR DESCRIPTION
**Pull request by Lermex**

### CODE REVIEW

**Comment by kingsleyh** [comment]
great thanks - but how does this work exactly?

**Comment by Neppord** [comment]
Is there a reason for this not being merged?

I would love to help out!

**Comment by kingsleyh** [comment]
Hi - sorry I haven't worked on this for a few years and don't plan on doing any more work to it - however if someone wants to take it over I can give access

**Comment by Neppord** [comment]
@kingsleyh I would love to take over and continue on your great work!

**Comment by Neppord** [comment]
This patch is not needed anymore.

**Pull request closed without merging**
